### ISSUE TITLE
Can you, please, deploy our app?

### ISSUE THREAD

**Issue by IhorMarkevych** [CMU-IDS-2020/a3-mysterious-visualizing-scotties#1]
Hi!
If I understood correctly Professor today, any changes will be incorporated as we deploy to this github repo. If that's the case, can you, please, deploy our app, which is in `main.py` file?
Thank you!

**Comment by domoritz** [comment]
Your app is running at https://share.streamlit.io/cmu-ids-2020/a3-mysterious-visualizing-scotties/main.py
